{
 "title": "monitoramento barco",
 "description": "teste 1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "intensidade do giro do motor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "dataset": "projeto",
     "rawSql": "SELECT vibracao_motor, data_hora\r\nFROM dados_barco\r\nWHERE $__timeFilter(data_hora) \r\nGROUP BY data_hora, vibracao_motor\r\nORDER BY data_hora ASC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "mapa (localização)",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "dataset": "projeto",
     "rawSql": "SELECT latitude, longitude\r\nFROM dados_barco \r\nORDER BY data_hora DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "temperatura ar",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "projeto",
     "rawSql": "SELECT\r\n  data_hora,\r\n  AVG(temperatura_ar) as media_temp_ar\r\nFROM\r\n  dados_barco\r\nWHERE $__timeFilter(data_hora)\r\nGROUP BY\r\n data_hora\r\nORDER BY\r\n  data_hora ASC;"
    }
   ]
  },
  {
   "title": "direção",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "projeto",
     "rawSql": "SELECT\r\n    data_hora,\r\n    CASE direcao\r\n        WHEN 1 THEN 'Frente'   -- norte (frente)\r\n        WHEN 2 THEN 'Esquerda'  -- oeste (esquerda)\r\n        WHEN 3 THEN 'Direita'   -- leste (direita)\r\n        ELSE 'desconhecida'     -- padrao\r\n    END AS direcao_bussola\r\nFROM dados_barco\r\nWHERE $__timeFilter(data_hora) \r\nORDER BY data_hora ASC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "pressão tanque",
   "type": "bargauge",
   "description": "depois melhorar para mostrar o combustivel",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "projeto",
     "rawSql": "SELECT pressao_tanque, data_hora\r\nFROM dados_barco \r\nWHERE $__timeFilter(data_hora)\r\nGROUP BY data_hora, pressao_tanque\r\nORDER BY data_hora ASC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "umidade do ar",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "projeto",
     "rawSql": "SELECT umidade, data_hora\r\nFROM dados_barco\r\nGROUP BY data_hora, umidade\r\nORDER BY data_hora ASC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "variação de velocidade",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "dataset": "projeto",
     "rawSql": "SELECT data_hora, velocidade\r\nFROM dados_barco\r\nWHERE $__timeFilter(data_hora) \r\nGROUP BY data_hora, velocidade\r\nORDER BY data_hora ASC;"
    }
   ]
  },
  {
   "title": "historico de alerta",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "projeto",
     "rawSql": "SELECT * FROM alertas ORDER BY data_hora DESC"
    }
   ]
  },
  {
   "title": "pressao atmosferica",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "dataset": "projeto",
     "rawSql": "SELECT pressao_atmosferica, data_hora\r\nFROM dados_barco \r\nGROUP BY pressao_atmosferica, data_hora\r\nORDER BY data_hora ASC;"
    }
   ]
  }
 ]
}